name: Local Ironic Tests

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LOGDIR: /tmp/logs
    strategy:
      matrix:
        scenario:
        - empty
        - provnet
    steps:
    - name: Create logs directory
      run: mkdir -p /tmp/logs
    - name: Install podman
      run: sudo apt install -y podman
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> "${GITHUB_OUTPUT}"
    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Run and check local ironic
      run: ./test/local-ironic/run.sh "${{ matrix.scenario }}"
    - name: Collect logs
      run: ./test/local-ironic/collect-logs.sh
      if: always()
    - name: Upload logs artifacts
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: local-ironic-${{ matrix.scenario }}
        path: /tmp/logs/*
      if: always()
    - name: Tear down local ironic
      run: ./test/local-ironic/tear-down.sh "${{ matrix.scenario }}"
