name: Local Ironic Tests

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LOGDIR: /tmp/logs
    strategy:
      matrix:
        scenario:
        - empty
        - provnet
    steps:
    - name: Create logs directory
      run: mkdir -p /tmp/logs
    - name: Install podman
      run: sudo apt install -y podman
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> "${GITHUB_OUTPUT}"
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Run and check local ironic
      run: ./test/local-ironic/run.sh "${{ matrix.scenario }}"
    - name: Collect logs
      run: ./test/local-ironic/collect-logs.sh
      if: always()
    - name: Upload logs artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: local-ironic-${{ matrix.scenario }}
        path: /tmp/logs/*
      if: always()
    - name: Tear down local ironic
      run: ./test/local-ironic/tear-down.sh "${{ matrix.scenario }}"
